/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketRouteImport } from './routes/market'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as DataGuideRouteImport } from './routes/data-guide'
import { Route as CropSelectRouteImport } from './routes/crop-select'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatisticsIndexRouteImport } from './routes/statistics.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as StatisticsSelectRouteImport } from './routes/statistics.select'
import { Route as StatisticsVarietyRouteImport } from './routes/statistics.$variety'
import { Route as PriceVarietyRouteImport } from './routes/price.$variety'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications.settings'
import { Route as MarketCropRouteImport } from './routes/market.$crop'
import { Route as NotificationsSettingsIndexRouteImport } from './routes/notifications.settings.index'
import { Route as PriceVarietyAlertRouteImport } from './routes/price.$variety.alert'
import { Route as NotificationsSettingsNewRouteImport } from './routes/notifications.settings.new'
import { Route as NotificationsSettingsRuleIdRouteImport } from './routes/notifications.settings.$ruleId'
import { Route as MarketWholesaleMarketRouteImport } from './routes/market.wholesale.$market'
import { Route as MarketItemItemRouteImport } from './routes/market.item.$item'
import { Route as MarketAuctionIdRouteImport } from './routes/market.auction.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGuideRoute = DataGuideRouteImport.update({
  id: '/data-guide',
  path: '/data-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CropSelectRoute = CropSelectRouteImport.update({
  id: '/crop-select',
  path: '/crop-select',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsIndexRoute = StatisticsIndexRouteImport.update({
  id: '/statistics/',
  path: '/statistics/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const StatisticsSelectRoute = StatisticsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => StatisticsRoute,
} as any)
const StatisticsVarietyRoute = StatisticsVarietyRouteImport.update({
  id: '/$variety',
  path: '/$variety',
  getParentRoute: () => StatisticsRoute,
} as any)
const PriceVarietyRoute = PriceVarietyRouteImport.update({
  id: '/price/$variety',
  path: '/price/$variety',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NotificationsRoute,
} as any)
const MarketCropRoute = MarketCropRouteImport.update({
  id: '/$crop',
  path: '/$crop',
  getParentRoute: () => MarketRoute,
} as any)
const NotificationsSettingsIndexRoute =
  NotificationsSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NotificationsSettingsRoute,
  } as any)
const PriceVarietyAlertRoute = PriceVarietyAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => PriceVarietyRoute,
} as any)
const NotificationsSettingsNewRoute =
  NotificationsSettingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => NotificationsSettingsRoute,
  } as any)
const NotificationsSettingsRuleIdRoute =
  NotificationsSettingsRuleIdRouteImport.update({
    id: '/$ruleId',
    path: '/$ruleId',
    getParentRoute: () => NotificationsSettingsRoute,
  } as any)
const MarketWholesaleMarketRoute = MarketWholesaleMarketRouteImport.update({
  id: '/wholesale/$market',
  path: '/wholesale/$market',
  getParentRoute: () => MarketRoute,
} as any)
const MarketItemItemRoute = MarketItemItemRouteImport.update({
  id: '/item/$item',
  path: '/item/$item',
  getParentRoute: () => MarketRoute,
} as any)
const MarketAuctionIdRoute = MarketAuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => MarketRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/crop-select': typeof CropSelectRoute
  '/data-guide': typeof DataGuideRoute
  '/grades': typeof GradesRoute
  '/market': typeof MarketRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/prediction': typeof PredictionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/market/$crop': typeof MarketCropRoute
  '/notifications/settings': typeof NotificationsSettingsRouteWithChildren
  '/price/$variety': typeof PriceVarietyRouteWithChildren
  '/statistics/$variety': typeof StatisticsVarietyRoute
  '/statistics/select': typeof StatisticsSelectRoute
  '/market/': typeof MarketIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/market/auction/$id': typeof MarketAuctionIdRoute
  '/market/item/$item': typeof MarketItemItemRoute
  '/market/wholesale/$market': typeof MarketWholesaleMarketRoute
  '/notifications/settings/$ruleId': typeof NotificationsSettingsRuleIdRoute
  '/notifications/settings/new': typeof NotificationsSettingsNewRoute
  '/price/$variety/alert': typeof PriceVarietyAlertRoute
  '/notifications/settings/': typeof NotificationsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/crop-select': typeof CropSelectRoute
  '/data-guide': typeof DataGuideRoute
  '/grades': typeof GradesRoute
  '/prediction': typeof PredictionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/market/$crop': typeof MarketCropRoute
  '/price/$variety': typeof PriceVarietyRouteWithChildren
  '/statistics/$variety': typeof StatisticsVarietyRoute
  '/statistics/select': typeof StatisticsSelectRoute
  '/market': typeof MarketIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/statistics': typeof StatisticsIndexRoute
  '/market/auction/$id': typeof MarketAuctionIdRoute
  '/market/item/$item': typeof MarketItemItemRoute
  '/market/wholesale/$market': typeof MarketWholesaleMarketRoute
  '/notifications/settings/$ruleId': typeof NotificationsSettingsRuleIdRoute
  '/notifications/settings/new': typeof NotificationsSettingsNewRoute
  '/price/$variety/alert': typeof PriceVarietyAlertRoute
  '/notifications/settings': typeof NotificationsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/crop-select': typeof CropSelectRoute
  '/data-guide': typeof DataGuideRoute
  '/grades': typeof GradesRoute
  '/market': typeof MarketRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/prediction': typeof PredictionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/market/$crop': typeof MarketCropRoute
  '/notifications/settings': typeof NotificationsSettingsRouteWithChildren
  '/price/$variety': typeof PriceVarietyRouteWithChildren
  '/statistics/$variety': typeof StatisticsVarietyRoute
  '/statistics/select': typeof StatisticsSelectRoute
  '/market/': typeof MarketIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/statistics/': typeof StatisticsIndexRoute
  '/market/auction/$id': typeof MarketAuctionIdRoute
  '/market/item/$item': typeof MarketItemItemRoute
  '/market/wholesale/$market': typeof MarketWholesaleMarketRoute
  '/notifications/settings/$ruleId': typeof NotificationsSettingsRuleIdRoute
  '/notifications/settings/new': typeof NotificationsSettingsNewRoute
  '/price/$variety/alert': typeof PriceVarietyAlertRoute
  '/notifications/settings/': typeof NotificationsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/crop-select'
    | '/data-guide'
    | '/grades'
    | '/market'
    | '/notifications'
    | '/prediction'
    | '/search'
    | '/settings'
    | '/watchlist'
    | '/market/$crop'
    | '/notifications/settings'
    | '/price/$variety'
    | '/statistics/$variety'
    | '/statistics/select'
    | '/market/'
    | '/notifications/'
    | '/statistics/'
    | '/market/auction/$id'
    | '/market/item/$item'
    | '/market/wholesale/$market'
    | '/notifications/settings/$ruleId'
    | '/notifications/settings/new'
    | '/price/$variety/alert'
    | '/notifications/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/crop-select'
    | '/data-guide'
    | '/grades'
    | '/prediction'
    | '/search'
    | '/settings'
    | '/watchlist'
    | '/market/$crop'
    | '/price/$variety'
    | '/statistics/$variety'
    | '/statistics/select'
    | '/market'
    | '/notifications'
    | '/statistics'
    | '/market/auction/$id'
    | '/market/item/$item'
    | '/market/wholesale/$market'
    | '/notifications/settings/$ruleId'
    | '/notifications/settings/new'
    | '/price/$variety/alert'
    | '/notifications/settings'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/crop-select'
    | '/data-guide'
    | '/grades'
    | '/market'
    | '/notifications'
    | '/prediction'
    | '/search'
    | '/settings'
    | '/watchlist'
    | '/market/$crop'
    | '/notifications/settings'
    | '/price/$variety'
    | '/statistics/$variety'
    | '/statistics/select'
    | '/market/'
    | '/notifications/'
    | '/statistics/'
    | '/market/auction/$id'
    | '/market/item/$item'
    | '/market/wholesale/$market'
    | '/notifications/settings/$ruleId'
    | '/notifications/settings/new'
    | '/price/$variety/alert'
    | '/notifications/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  CropSelectRoute: typeof CropSelectRoute
  DataGuideRoute: typeof DataGuideRoute
  GradesRoute: typeof GradesRoute
  MarketRoute: typeof MarketRouteWithChildren
  NotificationsRoute: typeof NotificationsRouteWithChildren
  PredictionRoute: typeof PredictionRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  PriceVarietyRoute: typeof PriceVarietyRouteWithChildren
  StatisticsIndexRoute: typeof StatisticsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-guide': {
      id: '/data-guide'
      path: '/data-guide'
      fullPath: '/data-guide'
      preLoaderRoute: typeof DataGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-select': {
      id: '/crop-select'
      path: '/crop-select'
      fullPath: '/crop-select'
      preLoaderRoute: typeof CropSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics/': {
      id: '/statistics/'
      path: '/statistics'
      fullPath: '/statistics/'
      preLoaderRoute: typeof StatisticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/statistics/select': {
      id: '/statistics/select'
      path: '/select'
      fullPath: '/statistics/select'
      preLoaderRoute: typeof StatisticsSelectRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/$variety': {
      id: '/statistics/$variety'
      path: '/$variety'
      fullPath: '/statistics/$variety'
      preLoaderRoute: typeof StatisticsVarietyRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/price/$variety': {
      id: '/price/$variety'
      path: '/price/$variety'
      fullPath: '/price/$variety'
      preLoaderRoute: typeof PriceVarietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/market/$crop': {
      id: '/market/$crop'
      path: '/$crop'
      fullPath: '/market/$crop'
      preLoaderRoute: typeof MarketCropRouteImport
      parentRoute: typeof MarketRoute
    }
    '/notifications/settings/': {
      id: '/notifications/settings/'
      path: '/'
      fullPath: '/notifications/settings/'
      preLoaderRoute: typeof NotificationsSettingsIndexRouteImport
      parentRoute: typeof NotificationsSettingsRoute
    }
    '/price/$variety/alert': {
      id: '/price/$variety/alert'
      path: '/alert'
      fullPath: '/price/$variety/alert'
      preLoaderRoute: typeof PriceVarietyAlertRouteImport
      parentRoute: typeof PriceVarietyRoute
    }
    '/notifications/settings/new': {
      id: '/notifications/settings/new'
      path: '/new'
      fullPath: '/notifications/settings/new'
      preLoaderRoute: typeof NotificationsSettingsNewRouteImport
      parentRoute: typeof NotificationsSettingsRoute
    }
    '/notifications/settings/$ruleId': {
      id: '/notifications/settings/$ruleId'
      path: '/$ruleId'
      fullPath: '/notifications/settings/$ruleId'
      preLoaderRoute: typeof NotificationsSettingsRuleIdRouteImport
      parentRoute: typeof NotificationsSettingsRoute
    }
    '/market/wholesale/$market': {
      id: '/market/wholesale/$market'
      path: '/wholesale/$market'
      fullPath: '/market/wholesale/$market'
      preLoaderRoute: typeof MarketWholesaleMarketRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/item/$item': {
      id: '/market/item/$item'
      path: '/item/$item'
      fullPath: '/market/item/$item'
      preLoaderRoute: typeof MarketItemItemRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/auction/$id': {
      id: '/market/auction/$id'
      path: '/auction/$id'
      fullPath: '/market/auction/$id'
      preLoaderRoute: typeof MarketAuctionIdRouteImport
      parentRoute: typeof MarketRoute
    }
  }
}

interface MarketRouteChildren {
  MarketCropRoute: typeof MarketCropRoute
  MarketIndexRoute: typeof MarketIndexRoute
  MarketAuctionIdRoute: typeof MarketAuctionIdRoute
  MarketItemItemRoute: typeof MarketItemItemRoute
  MarketWholesaleMarketRoute: typeof MarketWholesaleMarketRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketCropRoute: MarketCropRoute,
  MarketIndexRoute: MarketIndexRoute,
  MarketAuctionIdRoute: MarketAuctionIdRoute,
  MarketItemItemRoute: MarketItemItemRoute,
  MarketWholesaleMarketRoute: MarketWholesaleMarketRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface NotificationsSettingsRouteChildren {
  NotificationsSettingsRuleIdRoute: typeof NotificationsSettingsRuleIdRoute
  NotificationsSettingsNewRoute: typeof NotificationsSettingsNewRoute
  NotificationsSettingsIndexRoute: typeof NotificationsSettingsIndexRoute
}

const NotificationsSettingsRouteChildren: NotificationsSettingsRouteChildren = {
  NotificationsSettingsRuleIdRoute: NotificationsSettingsRuleIdRoute,
  NotificationsSettingsNewRoute: NotificationsSettingsNewRoute,
  NotificationsSettingsIndexRoute: NotificationsSettingsIndexRoute,
}

const NotificationsSettingsRouteWithChildren =
  NotificationsSettingsRoute._addFileChildren(
    NotificationsSettingsRouteChildren,
  )

interface NotificationsRouteChildren {
  NotificationsSettingsRoute: typeof NotificationsSettingsRouteWithChildren
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsSettingsRoute: NotificationsSettingsRouteWithChildren,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface PriceVarietyRouteChildren {
  PriceVarietyAlertRoute: typeof PriceVarietyAlertRoute
}

const PriceVarietyRouteChildren: PriceVarietyRouteChildren = {
  PriceVarietyAlertRoute: PriceVarietyAlertRoute,
}

const PriceVarietyRouteWithChildren = PriceVarietyRoute._addFileChildren(
  PriceVarietyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  CropSelectRoute: CropSelectRoute,
  DataGuideRoute: DataGuideRoute,
  GradesRoute: GradesRoute,
  MarketRoute: MarketRouteWithChildren,
  NotificationsRoute: NotificationsRouteWithChildren,
  PredictionRoute: PredictionRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  PriceVarietyRoute: PriceVarietyRouteWithChildren,
  StatisticsIndexRoute: StatisticsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
