/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MarketRouteImport } from './routes/market'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as StatisticsSelectRouteImport } from './routes/statistics.select'
import { Route as StatisticsVarietyRouteImport } from './routes/statistics.$variety'
import { Route as PriceVarietyRouteImport } from './routes/price.$variety'
import { Route as MarketCropRouteImport } from './routes/market.$crop'
import { Route as PriceVarietyAlertRouteImport } from './routes/price.$variety.alert'
import { Route as MarketWholesaleMarketRouteImport } from './routes/market.wholesale.$market'
import { Route as MarketItemItemRouteImport } from './routes/market.item.$item'
import { Route as MarketAuctionIdRouteImport } from './routes/market.auction.$id'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const StatisticsSelectRoute = StatisticsSelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => StatisticsRoute,
} as any)
const StatisticsVarietyRoute = StatisticsVarietyRouteImport.update({
  id: '/$variety',
  path: '/$variety',
  getParentRoute: () => StatisticsRoute,
} as any)
const PriceVarietyRoute = PriceVarietyRouteImport.update({
  id: '/price/$variety',
  path: '/price/$variety',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketCropRoute = MarketCropRouteImport.update({
  id: '/$crop',
  path: '/$crop',
  getParentRoute: () => MarketRoute,
} as any)
const PriceVarietyAlertRoute = PriceVarietyAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => PriceVarietyRoute,
} as any)
const MarketWholesaleMarketRoute = MarketWholesaleMarketRouteImport.update({
  id: '/wholesale/$market',
  path: '/wholesale/$market',
  getParentRoute: () => MarketRoute,
} as any)
const MarketItemItemRoute = MarketItemItemRouteImport.update({
  id: '/item/$item',
  path: '/item/$item',
  getParentRoute: () => MarketRoute,
} as any)
const MarketAuctionIdRoute = MarketAuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => MarketRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/grades': typeof GradesRoute
  '/market': typeof MarketRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/prediction': typeof PredictionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/market/$crop': typeof MarketCropRoute
  '/price/$variety': typeof PriceVarietyRouteWithChildren
  '/statistics/$variety': typeof StatisticsVarietyRoute
  '/statistics/select': typeof StatisticsSelectRoute
  '/market/': typeof MarketIndexRoute
  '/market/auction/$id': typeof MarketAuctionIdRoute
  '/market/item/$item': typeof MarketItemItemRoute
  '/market/wholesale/$market': typeof MarketWholesaleMarketRoute
  '/price/$variety/alert': typeof PriceVarietyAlertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/grades': typeof GradesRoute
  '/notifications': typeof NotificationsRoute
  '/prediction': typeof PredictionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/market/$crop': typeof MarketCropRoute
  '/price/$variety': typeof PriceVarietyRouteWithChildren
  '/statistics/$variety': typeof StatisticsVarietyRoute
  '/statistics/select': typeof StatisticsSelectRoute
  '/market': typeof MarketIndexRoute
  '/market/auction/$id': typeof MarketAuctionIdRoute
  '/market/item/$item': typeof MarketItemItemRoute
  '/market/wholesale/$market': typeof MarketWholesaleMarketRoute
  '/price/$variety/alert': typeof PriceVarietyAlertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/grades': typeof GradesRoute
  '/market': typeof MarketRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/prediction': typeof PredictionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/market/$crop': typeof MarketCropRoute
  '/price/$variety': typeof PriceVarietyRouteWithChildren
  '/statistics/$variety': typeof StatisticsVarietyRoute
  '/statistics/select': typeof StatisticsSelectRoute
  '/market/': typeof MarketIndexRoute
  '/market/auction/$id': typeof MarketAuctionIdRoute
  '/market/item/$item': typeof MarketItemItemRoute
  '/market/wholesale/$market': typeof MarketWholesaleMarketRoute
  '/price/$variety/alert': typeof PriceVarietyAlertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/grades'
    | '/market'
    | '/notifications'
    | '/prediction'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/watchlist'
    | '/market/$crop'
    | '/price/$variety'
    | '/statistics/$variety'
    | '/statistics/select'
    | '/market/'
    | '/market/auction/$id'
    | '/market/item/$item'
    | '/market/wholesale/$market'
    | '/price/$variety/alert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/grades'
    | '/notifications'
    | '/prediction'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/watchlist'
    | '/market/$crop'
    | '/price/$variety'
    | '/statistics/$variety'
    | '/statistics/select'
    | '/market'
    | '/market/auction/$id'
    | '/market/item/$item'
    | '/market/wholesale/$market'
    | '/price/$variety/alert'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/grades'
    | '/market'
    | '/notifications'
    | '/prediction'
    | '/search'
    | '/settings'
    | '/statistics'
    | '/watchlist'
    | '/market/$crop'
    | '/price/$variety'
    | '/statistics/$variety'
    | '/statistics/select'
    | '/market/'
    | '/market/auction/$id'
    | '/market/item/$item'
    | '/market/wholesale/$market'
    | '/price/$variety/alert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  GradesRoute: typeof GradesRoute
  MarketRoute: typeof MarketRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PredictionRoute: typeof PredictionRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  PriceVarietyRoute: typeof PriceVarietyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/statistics/select': {
      id: '/statistics/select'
      path: '/select'
      fullPath: '/statistics/select'
      preLoaderRoute: typeof StatisticsSelectRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/statistics/$variety': {
      id: '/statistics/$variety'
      path: '/$variety'
      fullPath: '/statistics/$variety'
      preLoaderRoute: typeof StatisticsVarietyRouteImport
      parentRoute: typeof StatisticsRoute
    }
    '/price/$variety': {
      id: '/price/$variety'
      path: '/price/$variety'
      fullPath: '/price/$variety'
      preLoaderRoute: typeof PriceVarietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$crop': {
      id: '/market/$crop'
      path: '/$crop'
      fullPath: '/market/$crop'
      preLoaderRoute: typeof MarketCropRouteImport
      parentRoute: typeof MarketRoute
    }
    '/price/$variety/alert': {
      id: '/price/$variety/alert'
      path: '/alert'
      fullPath: '/price/$variety/alert'
      preLoaderRoute: typeof PriceVarietyAlertRouteImport
      parentRoute: typeof PriceVarietyRoute
    }
    '/market/wholesale/$market': {
      id: '/market/wholesale/$market'
      path: '/wholesale/$market'
      fullPath: '/market/wholesale/$market'
      preLoaderRoute: typeof MarketWholesaleMarketRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/item/$item': {
      id: '/market/item/$item'
      path: '/item/$item'
      fullPath: '/market/item/$item'
      preLoaderRoute: typeof MarketItemItemRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/auction/$id': {
      id: '/market/auction/$id'
      path: '/auction/$id'
      fullPath: '/market/auction/$id'
      preLoaderRoute: typeof MarketAuctionIdRouteImport
      parentRoute: typeof MarketRoute
    }
  }
}

interface MarketRouteChildren {
  MarketCropRoute: typeof MarketCropRoute
  MarketIndexRoute: typeof MarketIndexRoute
  MarketAuctionIdRoute: typeof MarketAuctionIdRoute
  MarketItemItemRoute: typeof MarketItemItemRoute
  MarketWholesaleMarketRoute: typeof MarketWholesaleMarketRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketCropRoute: MarketCropRoute,
  MarketIndexRoute: MarketIndexRoute,
  MarketAuctionIdRoute: MarketAuctionIdRoute,
  MarketItemItemRoute: MarketItemItemRoute,
  MarketWholesaleMarketRoute: MarketWholesaleMarketRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface StatisticsRouteChildren {
  StatisticsVarietyRoute: typeof StatisticsVarietyRoute
  StatisticsSelectRoute: typeof StatisticsSelectRoute
}

const StatisticsRouteChildren: StatisticsRouteChildren = {
  StatisticsVarietyRoute: StatisticsVarietyRoute,
  StatisticsSelectRoute: StatisticsSelectRoute,
}

const StatisticsRouteWithChildren = StatisticsRoute._addFileChildren(
  StatisticsRouteChildren,
)

interface PriceVarietyRouteChildren {
  PriceVarietyAlertRoute: typeof PriceVarietyAlertRoute
}

const PriceVarietyRouteChildren: PriceVarietyRouteChildren = {
  PriceVarietyAlertRoute: PriceVarietyAlertRoute,
}

const PriceVarietyRouteWithChildren = PriceVarietyRoute._addFileChildren(
  PriceVarietyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  GradesRoute: GradesRoute,
  MarketRoute: MarketRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PredictionRoute: PredictionRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  PriceVarietyRoute: PriceVarietyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
